### ISSUE TITLE
Typos in  erasynth-micro-docs/erasynth-micro-command-list.pdf examples

### ISSUE THREAD

**Issue by bvernoux** [erainstruments/erasynth-micro-docs#1]
Typos in several examples of documentation https://github.com/erainstruments/erasynth-micro-docs/blob/master/erasynth-micro-command-list.pdf :
* Command **>SA{0}** 
`e.g. >A-15 sets -15 dBm. Resolution is 1 dB.`
Shall be replaced by
`e.g. >SA-15 sets -15 dBm. Resolution is 1 dB.`

* Command **>SMF{0}** 
`e.g >M31000 sets 1 kHz`
Shall be replaced by
`e.g >SMF1000 sets 1 kHz`

* Commands **>SMA{0} / >SMFD{0} / >SMPP{0} & >SMPW{0}** have similar typos as before in each e.g. with >M instead of the corresponding command

* Commands **>SS1{0}  / >SS2{0}  / >SS3{0}  & >SS4{0}** have similar typos as before in each e.g. with >S instead of the corresponding command

Thanks to fixes those typos in each e.g. as it is a bit confusing

**Comment by berjk** [comment]
Thanks for feedback. Those typos are corrected now.
